CREATE TABLE Person(
                       id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       name varchar(100) NOT NULL,
                       age int CHECK ( age<100 )
);

CREATE TABLE Item(
                     id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                     person_id int REFERENCES Person(id) ON DELETE SET NULL,
                     item_name varchar(100) NOT NULL
);

INSERT INTO Person(name, age) VALUES ('Tom', 35);


INSERT INTO item(person_id, item_name) VALUES (1, 'Book');
INSERT INTO item(person_id, item_name) VALUES (1, 'AirPods');
INSERT INTO item(person_id, item_name) VALUES (1, 'iPhone');
